package ServerObjectInterfaceApp;


/**
* ServerObjectInterfaceApp/ServerObjectInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerObjectInterface.idl
* Saturday, 25 February, 2023 9:01:57 AM IST
*/

public interface ServerObjectInterface extends ServerObjectInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerObjectInterface
